select * FROM raterapi_category;
select * FROM raterapi_designer;
select * FROM raterapi_game;
select * FROM raterapi_gamecategory;
select * FROM raterapi_image;
select * FROM raterapi_player;
select * FROM raterapi_review;
select * FROM authtoken_token;
select * FROM auth_user;
