# Generated by Django 3.1.3 on 2020-11-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designer',
            old_name='Name',
            new_name='name',
        ),
    ]
