# Generated by Django 3.1.3 on 2020-11-06 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0002_auto_20201106_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designer',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='designer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='raterapi.designer'),
            preserve_default=False,
        ),
    ]
